CREATE TABLE `hotels` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`title` text,
	`iata` text NOT NULL,
	`workflow_url` text,
	`crew` text,
	`effective_from` text,
	`effective_to` text,
	`name` text NOT NULL,
	`tel` text,
	`fax` text,
	`web` text,
	`email` text,
	`address` text,
	`discounts_available` text,
	`host` integer DEFAULT false NOT NULL,
	`internet` text,
	`health_club` text,
	`comments` text,
	`transport_provider` text,
	`transport_phone` text,
	`transport_email` text,
	`hotel_room_specification` text,
	`source_modified` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
